Remove defaults.yaml
iter8-tools/etc3 pull request #163
Opened 2021-03-17 20:41 UTC by kalantar

Addresses issue https://github.com/iter8-tools/etc3/issues/138

2021-03-17 20:43 UTC, kalantar commented
Also fixed a bug in `controllers/weights.go`

2021-03-22 19:26 UTC, sriumcp requested changes
None handler seems to require changes (removal?)

2021-03-22 19:26 UTC, sriumcp commented on api/v2alpha2/defaults.go
>  	// NoneHandler is the keyword users can use to indicate no handler
Why do we have this string "None" when handler itself is gone away? In any case, the comment doesn't seem right (users no longer indicate none handler through keywords).

2021-03-22 19:35 UTC, kalantar commented on api/v2alpha2/defaults.go
>  	// NoneHandler is the keyword users can use to indicate no handler
Good catch. Fixed.

2021-03-22 19:53 UTC, sriumcp approved these changes
lgtm

2021-03-22 19:56 UTC, merged