move spec.metrics to status.metrics
iter8-tools/etc3 pull request #180
Opened 2021-03-24 20:46 UTC by kalantar

2021-03-24 21:11 UTC, sriumcp requested changes

2021-03-24 21:11 UTC, sriumcp commented on controllers/metrics.go
> +func metricsRead(instance *v2alpha2.Experiment) bool {
I believe there is an infinite loop possibility here... 

What happens if the experiment has a non-nil criteria section, but there are no metric references within the criteria section (for example, there is an empty indicators list and an empty objectives list, and no request-count metric within criteria)... 

The way the check in line 74 is written, my understanding is that the above experiment (and other variants of it) will cause an infinite loop.

Can we capture this infinite loop within a (failing) test and fix it (perhaps, by modifying line 74?)... ensuring that the test passes?

2021-03-25 12:47 UTC, kalantar commented on controllers/metrics.go
> +func metricsRead(instance *v2alpha2.Experiment) bool {
Interesting. This hadn't occurred to me and was a flaw in the original code. Indeed, it causes the controller to crash (elsewhere) ; not just fail a test :)

2021-03-25 17:33 UTC, sriumcp approved these changes
lgtm

2021-03-25 17:36 UTC, merged