Support for synthetics
iter8-tools/etc3 pull request #210
Opened 2021-06-08 10:42 UTC by sriumcp

Signed-off-by: Srinivasan Parthasarathy <spartha@us.ibm.com>

Partly addresses #iter8-tools/iter8#742

2021-06-10 17:59 UTC, huang195 reviewed
Is the term `level` commonly used? Would it be more clear to call it `value`, so it takes the guessing work out of what it means when seeing `mock` and `value` together?

2021-06-10 20:41 UTC, huang195 commented
Neither is really clear, and I can't think of anything that is better at the moment. I guess it needs to be documented well.

2021-06-11 11:03 UTC, kalantar commented on api/v2alpha2/metric_types.go
> +	// For a counter metric, the level is used as a rate. Roughly speaking,
I see it clearly stated above in the PR conversation. Please add it to the comment as well.

2021-06-11 11:04 UTC, kalantar requested changes
one minor change requested

2021-06-11 13:12 UTC, sriumcp commented on api/v2alpha2/metric_types.go
> +	// For a counter metric, the level is used as a rate. Roughly speaking,
Done!

2021-06-11 14:38 UTC, kalantar approved these changes
lgtm

2021-06-11 14:46 UTC, merged