ensure request count read only once
iter8-tools/etc3 pull request #216
Opened 2021-07-29 12:59 UTC by kalantar

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>
ensure requestcount metric is read only once even when specified with and without namespace in the same experiment
addresses issue https://github.com/iter8-tools/iter8/issues/849

2021-07-29 13:19 UTC, kalantar commented
As part of this pull request, metrics specific tests were moved from `experiment_controller_test.go` to `metrics_test.go`. A new test was added -- it is the last one in the file.

2021-07-30 14:28 UTC, sriumcp requested changes
Minor change requested.

2021-07-30 14:28 UTC, sriumcp commented on controllers/metrics_test.go
> +	var goodObjective, goodObjective2, badObjective, reward *v2alpha2.Metric
Please rename goodObjective, and goodObjective2 as `goodMetric` and `goodMetric2` respectively.

2021-08-02 12:58 UTC, sriumcp commented on controllers/metrics_test.go
> +	var goodObjective, goodObjective2, badObjective, reward *v2alpha2.Metric
Other than this minor change, this PR looks good to merge.

2021-08-02 13:43 UTC, kalantar commented on controllers/metrics_test.go
> +	var goodObjective, goodObjective2, badObjective, reward *v2alpha2.Metric
renamed these and all the others as well.

2021-08-02 14:29 UTC, sriumcp approved these changes
lgtm

2021-08-02 14:33 UTC, merged