Remove Spec.VersionInfo
iter8-tools/etc3 pull request #236
Opened 2021-08-16 21:45 UTC by kalantar

addresses https://github.com/iter8-tools/iter8/issues/953

2021-08-16 21:56 UTC, sriumcp requested changes
changes requested re: baseline

2021-08-16 21:56 UTC, sriumcp commented on api/v2beta1/defaults.go
> +	return len(s.Versions) > 0
If we make `min = 1` for `Spec.VersionInfo`, then numVersions will always be 1 and we wouldn't need HasBaseline() at all.

I don't think the concept of baseline and candidate is useful in a conformance experiment.

2021-08-17 01:31 UTC, kalantar commented on api/v2beta1/defaults.go
> +	return len(s.Versions) > 0
I agree with you. I was going to say that it will probably go away on its own when we get through all the changes. But it appears that the only use was in test cases. So... its gone now.

2021-08-17 01:46 UTC, sriumcp approved these changes
lgtm

2021-08-17 11:08 UTC, merged