Remove metrics CRD
iter8-tools/etc3 pull request #239
Opened 2021-08-18 19:29 UTC by kalantar

Addresses issues https://github.com/iter8-tools/iter8/issues/930, https://github.com/iter8-tools/iter8/issues/934, and https://github.com/iter8-tools/iter8/issues/973.

2021-08-18 21:27 UTC, sriumcp requested changes
Change requested for metrics (which appear twice)

2021-08-18 21:27 UTC, sriumcp commented on api/v2beta1/experiment_types.go
> +	Metrics []Metric `json:"metrics,omitempty" yaml:"metrics,omitempty"`
This should go.

2021-08-19 11:53 UTC, kalantar commented on api/v2beta1/experiment_types.go
> +	Metrics []Metric `json:"metrics,omitempty" yaml:"metrics,omitempty"`
done

2021-08-19 22:17 UTC, sriumcp reviewed
We also said that we will *not* retain unknown fields. And CR cannot contain unknown fields. Is this how kubebuilder annotations are set now?

2021-08-19 22:17 UTC, sriumcp commented on api/v2beta1/defaults.go
>  	DefaultFailureHandler string = "finish"
We really don't have a concept of a failure handler. It is `start`, `loop` and `finish`. 

Could we please  remove FailureHandler related code please?

2021-08-19 22:24 UTC, sriumcp reviewed
We can also get rid of `NamedValue`.

I see that they are still used in two places.

1. Params for metrics, and 
2. Headers for metrics.

We can make them both maps.

This is related to your query the other day: are there really multiple params? Definitely not often. Probably infrequently. Anyway, we can cut out a line from both headers and params if we use maps instead of name-value pairs.

2021-08-19 22:24 UTC, sriumcp commented on test/data/withbackend.yaml
> +      - name: params
This looks super clean.

2021-08-20 12:15 UTC, kalantar commented on api/v2beta1/defaults.go
>  	DefaultFailureHandler string = "finish"
done

2021-08-20 12:18 UTC, kalantar commented
> We also said that we will not retain unknown fields. And CR cannot contain unknown fields. Is this how kubebuilder annotations are set now?

The default behavior is now implemented. We don't have any directives related to this.  The only place we find the property `x-kubernetes-preserve-unknown-fields: true` is in the generated crd file as a result of using:

 ```yaml
With map[string]apiextensionsv1.JSON
```

2021-08-20 13:27 UTC, sriumcp requested changes
1. Could we please remove comments related to target?  For example, stage initializing is now purely about start handler, not target acquisition: https://github.com/kalantar/etc3/blob/af921b1494b99d60e2f89fdae86a5775b9b7e60e/api/v2beta1/constants.go#L88

2. Could we please remove `MetricUnavailable` and `MetricUnreadable` reason codes from constants? Metric related validation is extremely important, and we need to provide proper support for it. But we need to think through how to achieve this comprehensively **within the analytics service**.  https://github.com/kalantar/etc3/blob/af921b1494b99d60e2f89fdae86a5775b9b7e60e/api/v2beta1/constants.go#L67

2021-08-20 13:49 UTC, kalantar commented
You managed to find the only use of the word "target" !  Fixed.

2021-08-20 16:24 UTC, sriumcp requested changes
This PR is almost there. I have two comments... 

1. We recently had an issue with `v2alpha` `run` task. Essentially, if both *task* and *run* are unspecified, the controller fails at the target acquisition stage, with no indication of why it was failing. Could we please introduce this check during validation (i.e., each task must contain exactly one of task or run but not both)? If it fails the check, we can fail the experiment with a *really understandable* failure code / reason. This would help in authoring as well as debugging.

2. While going through the handler parts of the controller logic, I saw a *commented out* portion that hardcodes the handler job structure (i.e., defines a batch/v1 job struct) instead of reading from the configmap. I believe this  is an extremely useful  alternative solution for what we currently have. This would basically knockout the whole handler configmap during installation, which is very desirable. Could we enable this approach? The only variable here would be handler image, which we can set as an environment variable for etc3.

2021-08-20 18:37 UTC, kalantar commented
Created issues https://github.com/iter8-tools/iter8/issues/982 and https://github.com/iter8-tools/iter8/issues/983 to address the suggested additional items. I would rather not add to this PR.

2021-08-20 19:19 UTC, sriumcp approved these changes
lgtm

2021-08-20 19:21 UTC, merged