Merge handler project into etc3
iter8-tools/etc3 pull request #240
Opened 2021-08-23 13:35 UTC by kalantar

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

2021-08-31 13:48 UTC, sriumcp requested changes
Please see review comments for iter8ctl.

2021-08-31 13:48 UTC, sriumcp commented on .github/workflows/build-and-push.yaml
> +        helmv3: 3.2.1
rename .github workflows to indicate the correct component. Example, `build-and-push-etc3.yaml`.

2021-08-31 13:48 UTC, sriumcp commented on Makefile
> +docker-build-taskrunner: ## Build docker image with the taskrunner
Are you able to build `iter8ctl` binary from this structure and run it as before? `go run` is ok for tests, but I want to check if you are able to build and `go get` iter8ctl using the current folder structure.

In particular, I want to check if `go` submodules are required for the three different projects (now) under etc3 or if we can get away with packages.

2021-08-31 18:20 UTC, kalantar commented on .github/workflows/build-and-push.yaml
> +        helmv3: 3.2.1
renamed.

2021-08-31 18:20 UTC, kalantar commented on Makefile
> +docker-build-taskrunner: ## Build docker image with the taskrunner
yes. for clarity added targets for each of the repos.

2021-08-31 23:23 UTC, sriumcp commented on Makefile
> +docker-build-taskrunner: ## Build docker image with the taskrunner
Could you please let me know the new `go get` command that I can use to install iter8ctl? It can target your fork for now (for manual testing / verification) purposes.

2021-09-01 13:20 UTC, kalantar commented on Makefile
> +docker-build-taskrunner: ## Build docker image with the taskrunner
Ah. Good question. I think the following but do not know how to test:

```bash
go install github.com/iter8-tools/etc3/iter8ctl@ref
```

(Note that using `go get` to install is deprecated starting in go 1.17; `go install` was introduced in go 1.16 which I think we require. See, for example, https://play-with-go.dev/installing-go-programs-directly_go116_en/)

2021-09-01 13:50 UTC, sriumcp commented on Makefile
> +docker-build-taskrunner: ## Build docker image with the taskrunner
Here's what I am getting... 

```shell
go install github.com/kalantar/etc3/iter8ctl@latest
go: downloading github.com/kalantar/etc3 v0.0.0-20210812154653-610d72f2f4e2
go install github.com/kalantar/etc3/iter8ctl@latest: module github.com/kalantar/etc3@latest found (v0.0.0-20210812154653-610d72f2f4e2), but does not contain package github.com/kalantar/etc3/iter8ctl
```

2021-09-01 13:53 UTC, sriumcp commented on Makefile
> +docker-build-taskrunner: ## Build docker image with the taskrunner
A bit more progress with this ...

```shell
go install github.com/kalantar/etc3/iter8ctl@mergerepos
go: downloading github.com/kalantar/etc3 v0.0.0-20210831181944-41acbb24bff8
go install github.com/kalantar/etc3/iter8ctl@mergerepos: github.com/kalantar/etc3@none updating to
	github.com/kalantar/etc3@v0.0.0-20210831181944-41acbb24bff8: parsing go.mod:
	module declares its path as: github.com/iter8-tools/etc3
	        but was required as: github.com/kalantar/etc3
```

For testing purposes, perhaps you could replace `iter8-tools` with `kalantar` in go mod and conform if `go install works`?

2021-09-01 13:54 UTC, kalantar commented on Makefile
> +docker-build-taskrunner: ## Build docker image with the taskrunner
I believe that you would need to use ref `mergerepos`. I get this:

```bash
$ go install github.com/kalantar/etc3/iter8ctl@mergerepos
go install github.com/kalantar/etc3/iter8ctl@mergerepos: github.com/kalantar/etc3@none updating to
	github.com/kalantar/etc3@v0.0.0-20210831181944-41acbb24bff8: parsing go.mod:
	module declares its path as: github.com/iter8-tools/etc3
	        but was required as: github.com/kalantar/etc3
```

2021-09-01 14:09 UTC, kalantar commented on Makefile
> +docker-build-taskrunner: ## Build docker image with the taskrunner
> For testing purposes, perhaps you could replace `iter8-tools` with `kalantar` in go mod and conform if `go install works`?

This would require changing every import statement in the project. This is why I find this hard to test in a reasonable way.

2021-09-01 14:33 UTC, sriumcp commented on Makefile
> +docker-build-taskrunner: ## Build docker image with the taskrunner
In this case, I suggest we create a `mergerepos` branch in etc3, merge it into the  `mergerepos` branch of etc3, and test it.

I actually suspect that the current project structure will not work, at least for `iter8ctl` install if not for `handler` executable creation as well, which is the reason for insisting on the test.

We definitely need a way of testing and confirming these changes work before merging into `etc3` main, because, otherwise, we are putting `etc3` into an unknown and potentially unusable condition for I am not sure how long.

2021-09-01 17:09 UTC, kalantar commented
Created new PR on upstream branch.

2021-09-01 17:09 UTC, closed without merging