late initialization and weight redistribution
iter8-tools/etc3 pull request #32
Opened 2020-11-23 20:53 UTC by kalantar

2020-11-23 22:10 UTC, sriumcp requested changes

2020-11-23 22:10 UTC, sriumcp commented on controllers/metrics.go
> +		r.markSpecUpdated()
markSpecUpdated() needs to change to markStatusUpdated()

2020-11-23 22:10 UTC, sriumcp commented on controllers/metrics.go
> +		r.markSpecUpdated()
Is it already updated? Or is there a pending update?

2020-11-23 22:10 UTC, sriumcp commented on controllers/recorder.go
>  		r.markSpecUpdated()
markSpecUpdated() doesn't belong here.

2020-11-24 01:18 UTC, kalantar commented on controllers/experiment_controller.go
> +	// LATE INITIALIZATION of spec
I've made some (minor) changes in names and approach. Let's review again. If we decide we should still do this, I would like to defer it.

2020-11-24 01:19 UTC, kalantar commented on controllers/experiment_controller.go
> +	change = r.ReadMetrics(ctx, instance) || change
I would like to defer this. I think what we have will get us to a fuller demonstration and then we can fix. In the meantime, we should introduce this concept for any new errors we want to capture in a similar way.

2020-11-24 01:19 UTC, kalantar commented on controllers/experiment_controller.go
> +	if r.StatusUpdated {
done

2020-11-24 01:19 UTC, kalantar commented on controllers/experiment_controller.go
> +func (r *ExperimentReconciler) finishExperiment(ctx context.Context, instance *v2alpha1.Experiment) (ctrl.Result, error) {
documented in the code

2020-11-24 01:19 UTC, kalantar commented on controllers/metrics.go
> +func (r *ExperimentReconciler) ReadMetrics(ctx context.Context, instance *v2alpha1.Experiment) bool {
done

2020-11-24 01:20 UTC, kalantar commented on controllers/metrics.go
> +		r.markSpecUpdated()
done

2020-11-24 01:20 UTC, kalantar commented on controllers/metrics.go
> +		r.markSpecUpdated()
renamed and eliminated the use of a method so hopefully clearer.

2020-11-24 01:20 UTC, kalantar commented on controllers/recorder.go
>  		r.markSpecUpdated()
done

2020-11-24 01:21 UTC, kalantar commented
I've pushed changes to address of the comments in a new commit.

2020-11-24 16:06 UTC, sriumcp approved these changes
LGTM for now.

2020-11-24 16:07 UTC, merged